const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const PORT=process.env.PORT||3000,DATA=path.join(__dirname,"bookings.json"),PUBLIC=__dirname;
if(!fs.existsSync(DATA))fs.writeFileSync(DATA,"[]");const read=()=>JSON.parse(fs.readFileSync(DATA,"utf8")),write=x=>fs.writeFileSync(DATA,JSON.stringify(x,null,2));
const SLOTS=["09:00 AM","09:30 AM","10:00 AM","10:30 AM","11:00 AM","11:30 AM","12:00 PM","12:30 PM","01:00 PM","01:30 PM","02:00 PM","02:30 PM","03:00 PM","03:30 PM","04:00 PM","04:30 PM","05:00 PM","05:30 PM","06:00 PM","06:30 PM","07:00 PM","07:30 PM","08:00 PM","08:30 PM"];
const send=(r,c,d,t="application/json")=>{r.writeHead(c,{"Content-Type":t,"Access-Control-Allow-Origin":"*"});r.end(t.includes("json")?JSON.stringify(d):d)},body=q=>new Promise((ok,no)=>{let b="";q.on("data",c=>b+=c);q.on("end",()=>{try{ok(JSON.parse(b||"{}"))}catch(e){no(e)}})});
http.createServer(async(req,res)=>{let u=new URL(req.url,"http://"+req.headers.host);
if(req.method==="GET"&&u.pathname==="/api/slots"){let date=u.searchParams.get("date"),booked=read().filter(x=>x.date===date&&x.status!=="Cancelled").map(x=>x.time);return send(res,200,{slots:SLOTS,booked})}
if(req.method==="GET"&&u.pathname==="/api/bookings")return send(res,200,read());
if(req.method==="POST"&&u.pathname==="/api/book"){let x=await body(req),b=read();if(!x.name||!x.phone||!x.service||!x.date||!x.time)return send(res,400,{error:"Fill all required fields"});if(b.some(y=>y.date===x.date&&y.time===x.time&&y.status!=="Cancelled"))return send(res,409,{error:"Slot already booked"});let z={id:crypto.randomUUID(),bookingNo:"SS-"+Math.floor(100000+Math.random()*900000),...x,status:"Booked"};b.push(z);write(b);return send(res,201,z)}
if(req.method==="PATCH"&&u.pathname.startsWith("/api/bookings/")){let id=u.pathname.split("/").pop(),b=read(),i=b.findIndex(x=>x.id===id);if(i<0)return send(res,404,{error:"Not found"});Object.assign(b[i],await body(req));write(b);return send(res,200,b[i])}
let f=u.pathname==="/"?"customer.html":u.pathname.slice(1),full=path.join(PUBLIC,f);fs.readFile(full,(e,d)=>{if(e)return send(res,404,"Not found","text/plain");let ext=path.extname(full),m={".html":"text/html",".css":"text/css",".js":"text/javascript"}[ext]||"application/octet-stream";send(res,200,d,m)})}).listen(PORT,()=>console.log("StyleSpot: http://localhost:"+PORT));